---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  network: 172.22.0.0/24
s1c:
  name: lte-s1c
  network: 172.21.1.0/24
s1u:
  name: lte-s1u
  network: 172.21.0.0/24
s5u:
  name: lte-s5u
  network: 172.25.0.0/24
s5c:
  name: lte-s5c
  network: 172.25.1.0/24
sgi:
  name: lte-sgi
  network: 10.0.1.0/24
  subnet: 10.0.1.0/24
euu:
  name: lte-euu
  network: 10.0.3.0/24
