---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s5u:
  name: lte-s5u
  network: 172.25.0.0/24
  interface: s5u1
s5c:
  name: lte-s5c
  network: 172.25.1.0/24
  interface: s5c2
sgi:
  name: lte-sgi
  network: 10.0.1.0/24
  interface: sgi3
  subnet: 10.0.1.0/24
etcd:
  url: http://lte-etcd.default.svc.cluster.local:12379

replicaCount: 1

image:
  repository: gwtester/pgw
  pullPolicy: IfNotPresent
  tag: latest

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
