---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s1c:
  name: lte-s1c
  network: 172.21.1.0/24
  interface: s1c2
s1u:
  name: lte-s1u
  network: 172.21.0.0/24
  interface: s1u3
euu:
  name: lte-euu
  network: 10.0.3.0/24
  interface: euu1

replicaCount: 1

image:
  repository: electrocucaracha/enb
  pullPolicy: IfNotPresent
  tag: 0.7.5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
