---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  network: 172.22.0.0/24
  interface: s111
s1u:
  name: lte-s1u
  network: 172.21.0.0/24
  interface: s1u2
s5u:
  name: lte-s5u
  network: 172.25.0.0/24
  interface: s5u3
s5c:
  name: lte-s5c
  network: 172.25.1.0/24
  interface: s5c4

replicaCount: 1

image:
  repository: electrocucaracha/sgw
  pullPolicy: IfNotPresent
  tag: 0.7.5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
