---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgw.fullname" . }}
  labels:
    {{- include "pgw.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "pgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {"name": "{{ .Values.s5u.name }}", "interface": "{{ .Values.s5u.interface }}"},
            {"name": "{{ .Values.s5c.name }}", "interface": "{{ .Values.s5c.interface }}"},
            {"name": "{{ .Values.sgi.name }}", "interface": "{{ .Values.sgi.interface }}"}
          ]
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"default"},
            {"clusterNetwork":"{{ .Values.s5u.name }}"},
            {"clusterNetwork":"{{ .Values.s5c.name }}"},
            {"clusterNetwork":"{{ .Values.sgi.name }}"}
          ]
        ns.networkservicemesh.io/endpoints: |
          {
            "name": "lte-network",
            "networkServices": [
              {"link": "sgi", "labels": "app=http-server-sgi", "ipaddress": "{{ .Values.sgi.networkId }}/{{ .Values.sgi.networkLength }}", "route": "{{ .Values.euu.networkId }}/{{ .Values.euu.networkLength }}"},
              {"link": "s5u", "labels": "app=pgw-s5u", "ipaddress": "{{ .Values.s5u.networkId }}/{{ .Values.s5u.networkLength }}"},
              {"link": "s5c", "labels": "app=pgw-s5c", "ipaddress": "{{ .Values.s5c.networkId }}/{{ .Values.s5c.networkLength }}"}
            ]
          }
      labels:
        network: pdn
        {{- include "pgw.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: debug
            - name: S5U_NETWORK
              value: "{{ .Values.s5u.networkId }}/{{ .Values.s5u.networkLength }}"
            - name: S5C_NETWORK
              value: "{{ .Values.s5c.networkId }}/{{ .Values.s5c.networkLength }}"
            - name: SGI_NIC
              value: "{{ .Values.sgi.interface }}"
            - name: SGI_SUBNET
              value: "{{ .Values.sgi.subnet }}"
            - name: ETCD_URL
              value: "{{ .Values.etcd.url }}"
