---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  networkId: 172.22.0.0
  networkLength: 24
  interface: s111
s1c:
  name: lte-s1c
  networkId: 172.21.1.0
  networkLength: 24
  interface: s1c2

replicaCount: 1

image:
  repository: electrocucaracha/mme
  pullPolicy: IfNotPresent
  tag: 0.7.5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
